### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by cshaa** [leongrdic/wsl-alias#1]
On my Windows, the real path to WSL is `C:\Users\micha\AppData\Local\lxss\home\m93a\.wsl`, not `%localappdata%\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\m93a\.wsl` as your program reports.

**Comment by leongrdic** [comment]
Thanks for trying out `easyWSLbash`!
I can see that you're running an older build version of Windows 10, because your WSL is installed via the LXSS. However, this script uses some features that were introduced in later builds.
You should opt in to Windows Insider program and get the newest build and then install Ubuntu through the Windows Store. I think you might have to uninstall the LXSS version first (using `lxrun /uninstall`) so back up any important data.
I will update the readme with info on why this project requires the 16215 build and what features aren't available before it.

**Comment by leongrdic** [comment]
Finally updated [the readme](https://github.com/leongrdic/easyWSLbash#why-does-it-require-the-insider-builds). Closing the issue. If you should find any more problems, please report them!
